name: Build and Release Ethereum Block Exporter

on:
  push:
    branches: [ main ]
    paths:
      - './ethereum-blocks-exporter/**'
  pull_request:
    branches: [ main ]
    paths:
      - './ethereum-blocks-exporter/**'
  release:
    types: [created]

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./injective/ethereum-blocks-exporter
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
          args: release --clean
          workdir: ./ethereum-blocks-exporter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
