name: Build and Push Docker Image for umee-pricefeeder-exporter
on:
  push:
    branches: [ main ]
    paths:
      - 'umee/umee-pricefeeder-exporter/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Check Out Repository
      uses: actions/checkout@v2

    - name: Lowercase Repository Owner
      id: repo_owner
      run: echo "REPO_OWNER=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GH_TOKEN }}

    - name: Build and Push Docker image for umee-pricefeeder-exporter
      uses: docker/build-push-action@v2
      with:
        context: ./umee/umee-pricefeeder-exporter
        file: ./umee/umee-pricefeeder-exporter/Dockerfile
        push: true
        tags: ghcr.io/${{ env.REPO_OWNER }}/umee-pricefeeder-exporter:latest
