name: Build and Push Docker Image for Berachain ETH exporter exporter
on:
  push:
    branches: [ main ]
    paths:
      - 'berachain-eth-exporter/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Check Out Repository
      uses: actions/checkout@v2

    - name: Lowercase Repository Owner
      id: repo_owner
      run: echo "REPO_OWNER=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GH_TOKEN }}

    - name: Build and Push Docker image for Berachain ETH exporter exporter
      uses: docker/build-push-action@v2
      with:
        context: ./berachain-eth-exporter
        file: ./berachain-eth-exporter/Dockerfile
        push: true
        tags: ghcr.io/${{ env.REPO_OWNER }}/berachain-eth-exporter:latest
